version: "3.8"

networks:
  mybackendcontainers:
    name: mybackendcontainers
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: "mariadb:10.5.8"
    restart: always
    hostname: mariadb
    networks:
      - mybackendcontainers
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: majorbackend
      MYSQL_USER: majorek
      MYSQL_PASSWORD: test1
      MYSQL_ROOT_PASSWORD: test2

  mybackendapp:
    container_name: mybackendapp
#    build: .
    image: mybackendapp-mybackendapp
#    restart: always
    ports:
      - "1000:443"
    networks:
      - mybackendcontainers
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_NAME: majorbackend
      DB_USER: majorek
      DB_PORT: 3306
      DB_PASS: test1
      X_USER_NAME: user
      HASHED_PASS: "$2a$06$6WVrmNTsLz/URgtb0RVXIueLNx9u.PABjntEGjkkVmpXxwnx7VS5m"
      JWT_SECRET: dupajasiu
      KEY_STORE_ALIAS: major.ovh
#      KEY_STORE_LOCATION: src/main/resources/keystore/major.p12
      KEY_STORE_LOCATION: classpath:major.p12
      KEY_STORE_PASS: 127Sfgt
