version: "3.7"


services:
  mariadb:
    container_name: mariadbtest
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: majorbackendtests
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test1
      MYSQL_ROOT_PASSWORD: test2