app_user:
  name: ${X_USER_NAME}
  hashedPassword: ${HASHED_PASS}

auth:
  jwt:
    expirationDays: 1
    secret: ${JWT_SECRET}
    issuer: my-backend

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT

server:
  ssl:
    key-store: src/main/resources/keystore/major.p12
    key-store-password: ${KEY_STORE_PASS}
    key-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: major.ovh
  port: 443

