app_user:
  name: ${X_USER_NAME}
  hashedPassword: ${HASHED_PASS}

auth:
  jwt:
    expirationDays: 1
    secret: ${JWT_SECRET}
    issuer: my-backend

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT

spring:
  jpa:
    #show-sql: true
    hibernate:
      #It is a good security practice to, after your database is in a production state, set this to none, revoke all
      #privileges from the MySQL user connected to the Spring application, and give the MySQL user only SELECT, UPDATE, INSERT, and DELETE.
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always

server:
  ssl:
    key-store: ${KEY_STORE_LOCATION}
    key-store-password: ${KEY_STORE_PASS}
    key-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: ${KEY_STORE_ALIAS}
  port: 443