app_user:
  name: ${X_USER_NAME}
  hashedPassword: ${HASHED_PASS}

auth:
  jwt:
    expirationDays: 1
    secret: ${JWT_SECRET}
    issuer: my-backend

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
#      username: "user"
#      password: "secret"
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
  flyway:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}
    locations: classpath:db/migrations
    baseline-on-migrate: true
  cache:
    type: redis
    redis:
      time-to-live: PT30S

server:
  ssl:
    key-store: ${KEY_STORE_LOCATION}
    key-store-password: ${KEY_STORE_PASS}
    key-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: ${KEY_STORE_ALIAS}
  port: 443