pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    def mvnHome = tool 'maven'
                    sh "${mvnHome}/bin/mvn test"
                }
            }
        }
    }
}